In [1]:
import numpy as np

## Vektörlerde İndeksleme

In [2]:
x = np.arange(2,20,2)
x

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
x[0],x[1],x[6]

(2, 4, 14)

### Tersten İndekslenmesi

In [10]:
x[-1],x[-2],x[-8]

(18, 16, 4)

### Arraylerde Slicing

In [11]:
x

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
x[0:9:1]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
# x arrayindeki 0. indeksten 9. indeksteki elemana kadar olan elemanlara ulaştık (9 indeksteki eleman dahil değildir)

In [15]:
x[:9:1]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
# başlangıç noktası boş bırakıldığında default olarak 0 atanır

In [17]:
x[2::1]

array([ 6,  8, 10, 12, 14, 16, 18])

In [18]:
# 2. indeksteki elemandan son elemana kadar olan elemanlar ulaştık (son eleman da dahil edilir)

In [19]:
x[3:8:2]

array([ 8, 12, 16])

In [20]:
# x arrayindeki 3. indeksli elemandan 8. indeksli elemana kadar olan elemanlara 2 adım ile ulaştık
# yani her ulaşılan elemandan sonraki 2. elemana ulaşır

In [21]:
x[2:9]

array([ 6,  8, 10, 12, 14, 16, 18])

In [22]:
# eğer adım parametresi girilmezse default 1 olarak atanır

In [23]:
x[:]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
# bütün elemanlarına ulaşır yani =x

#### Belirli indeksleri istenilen değerle doldurmak

In [26]:
x

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
x[1:9:2] = 1
x

array([ 2,  1,  6,  1, 10,  1, 14,  1, 18])

In [28]:
# slicing işlemi ile ulaştığımız elemanların değerini 1 ile değiştirdik

In [29]:
x[:3] = 4
x

array([ 4,  4,  4,  1, 10,  1, 14,  1, 18])

In [30]:
# ilk 3 elemanın değerini 4 ile değiştirdik

## Matrislerde İndeksleme

In [33]:
dizi = [[1,2],
       [4,6]]

In [34]:
y= np.array(dizi)
y

array([[1, 2],
       [4, 6]])

In [35]:
y[0,0]

1

y matrisindeki 0. indeksli satırdaki ve sütunda da 0. indekste bulunan elemana ulaştık

* matrislerde indeksleme işlemi önce satırla başlar
* ikinci istenilen indeks bilgisi ise sütun indeks bilgisidir

In [36]:
y[1,0]

4

In [37]:
# y matrisindeki 1. indeksli satırdaki ve sütunda da 0. indekste bulunan elemana ulaştık

### İki Boyutlu Arraylerde(Matrislerde) Slicing

In [44]:
m = np.random.randint(10,size = (5,5))
m

array([[2, 7, 2, 7, 1],
       [9, 6, 2, 7, 5],
       [0, 0, 2, 4, 3],
       [6, 7, 3, 3, 5],
       [3, 2, 7, 6, 2]])

Önce matrisimizdeki ilk sütuna erişmeyi deneyelim

In [45]:
m[:,0]

array([2, 9, 0, 6, 3])

In [46]:
# matrisimizdeki tüm satırları aldık,sütun olarak ise 0 indeksli sütunu aldık

Tercüme edecek olursak yukarıdaki kullanımla bütün satırları seç sonra da 0 indeksli sütunu seç dedik

In [47]:
m

array([[2, 7, 2, 7, 1],
       [9, 6, 2, 7, 5],
       [0, 0, 2, 4, 3],
       [6, 7, 3, 3, 5],
       [3, 2, 7, 6, 2]])

Şimdi de ilk satıra ulaşmayı deneyelim

In [49]:
m[0,:]

array([2, 7, 2, 7, 1])

In [50]:
# matristeki tüm sütunları aldık, satır olarak ise sadece 0. indeksli satırı aldık

In [51]:
m[1,:]

array([9, 6, 2, 7, 5])

şimdi de her iki boyut için de aralık belirterek elemanlara ulaşalım

In [52]:
m

array([[2, 7, 2, 7, 1],
       [9, 6, 2, 7, 5],
       [0, 0, 2, 4, 3],
       [6, 7, 3, 3, 5],
       [3, 2, 7, 6, 2]])

In [53]:
m[0:2,0:3]

array([[2, 7, 2],
       [9, 6, 2]])

In [54]:
# 0' dan 2'ye kadar olan satırdaki elemanları ve 0'dan 3'e kadar olan sütundaki elemanları aldık

In [55]:
m[1:3,0:2]

array([[9, 6],
       [0, 0]])

### Matrislerde Toplu elemana ulaşma (not slicing)

In [38]:
y

array([[1, 2],
       [4, 6]])

In [43]:
y[[0,1],[0,1]]

array([1, 6])

In [42]:
y[[0,0],[1,1]]

array([2, 2])

dikkat edilmesi gereken nokta boyutlar birbiriyle eşleşir

* ilk indekslemenin ilk 0'ı ile 2. indekslemenin ilk 1'i birbiriyle eşleşir
* ilk indekslemenin ikinci 0'ı ile 2. indekslemenin ikinci 1'i birbiriyle eşleşir
* yani ilk eleman olarak 0 indeksli satırdaki ve sütunda da 1. indekste bulunan elemana ulaştık
* ikinci eleman olarak da yine 0 indeksli satırdaki ve sütunda da 1. indekste bulunan elemana ulaştık