# Fancy Index ile Emanlara Erişmek

In [1]:
import numpy as np

In [2]:
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [3]:
[v[1],v[3],v[5]]

[3, 9, 15]

In [4]:
al_getir = [1,3,5]

In [5]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [6]:
v[al_getir]

array([ 3,  9, 15])

In [8]:
#array içinden çoklu eleman seçimini tek seferde gerçekleştirerilebilir

* al_getir adında bir liste tanımladık
* daha sonra elimizdeki arraye bu listeyi eleman seçme formatıyla yolladık
* listenin içindeki her bir elemana denk gelen indexteki elemanların tümünü seçtik

### iki boyutta (matriste) fancy index

In [9]:
m = np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [11]:
m[satir,sutun]

array([1, 5])

* satir adında yeni bir [0,1] vektörü oluşturduk
* sutun adında yeni bir [1,2] vektörü oluuşturduk
* ilk alınacak eleman için satır vektörünü,sonraki eleman için ise sutun vektörünü kullandık
* daha sonra matrise eleman seçme formatıyla bu vektörleri yolladık

#### basit index ile fancy index

In [13]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
m[0,[1,2]]

array([1, 2])

In [1]:
# basit index ile fancy indeksi bir arada kullandık

* m matrisindeki 0 indeksli satıra gittik
* 0 indeksli satırdaki 1 ve 2 indeksli sütun elemanlarını aldık

#### slice ile fancy index

In [16]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
m[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [18]:
# slice işlemi ile fancy işlemini aynı anda kullandık 

* slice işlemi ile ilk satırdan son satıra kadar gittik
* ve 1 ve 2. indeksli sütunları aldık