## arange

In [1]:
import numpy as np

In [2]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

* ilk parametreye başlangıç noktasını attık
* ikinci parametreye ise bitiş noktasını attık

alabileceği 3. bir parametre vardır, bu da adım parametresidir(tıpkı slicing işlemindeki gibi). Varsayılan step bilgisi 1'dir

yani burada 1 den 10 kadar değerlerden oluşan bir numpy vektörel array oluşturduk(10 dahil değildir)

In [3]:
x = np.arange(0,50,5,dtype = int)
x

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

Bu sefer 0'dan 50'ye kadar 5'er adımla giden bir array oluşturduk

dtype parametresi ile de içerik veri tipini dolayısıyla array veri tipini belirledik

##### Not: Eğer bir array içinde int verilerin dışında bir float veri var ise diğer int değerlerde floata çevrilerek sabit bir veri yapısı elde edilir

In [4]:
y = np.arange(0,5,dtype = complex)
y

array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

Kullanabileceğimiz bir diğer dtype değeri ise complex yani karmaşık sayıdır

In [5]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a.astype(bool)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

astype metodu array elemanlarının parametredeki veri tipindeki karşılıklarını döndürür. Örneğin float veri tipi de parametreye gönderilebilirdi

##### Not2: Aralık parametreleri float olarak verildiğinde ve dtype ile arrayin tipi int istendiğinde bütün elemanlar "0" olarak belirlenir
##### Bunu önlemek için array float değerlerle oluştuulduktan sonra astype metoduyla dönüştürülebilir

## inspace

In [7]:
x = np.linspace(1,10)
x

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

linspace metoduyla 1 ile 10 arasındaki sayılardan oluşan bir array oluşturduk.
Eğer bir eleman bilgisi parametresi girilmezse varsayılan olarak 50 elemandan oluşur

* ilk parametreye başlangıç noktasını yolladık
* ikinci parametreye ise bitiş noktasını yolladık (bitiş noktası array içine dahil edilir)

Alabileceği 3. bir parametre daha vardır: Bu parametre ise array içindeki eleman sayısını belirler

In [8]:
y = np.linspace(1,10,7)
y

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

In [9]:
# 7 elemanlı, 1 ile 10 sayıları arasındaki değerlerden oluşan bir array oluşturduk

In [10]:
z = np.linspace(1,10,9,endpoint = False)
z

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

endpoint parametresini False yaparak bitiş noktasının(10) dahil olmasını engelledik. Eğer False olarak işaretlenmezse varsayılan olarak True değeri aktiftir

In [11]:
a = np.linspace(1,10,7,retstep = True)
a

(array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ]), 1.5)

retstep parametresini True yaparak oluşturulan rastgele arrayin adım miktarını da döndürür

retstep kullanıldığında tuple tipinde bir çıktı döner ve ilk elemanı oluşturulan arraydir, ikinci elemanı ise arrayin adım miktarıdır

In [12]:
# dönen tuple elemanlarını farlı değişkenlere atayarak array ve adım miktarına teker teker ulaşabiliriz

In [13]:
arr,step = np.linspace(1,10,5,retstep = True)

In [14]:
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [15]:
step

2.25

In [16]:
# görüldüğü gibi oluşan arrayi arr değişkenine, adım bilgisini ise step değişkenine atadık