## Rastgele Örnekleme

In [1]:
import numpy as np

### np.random.rand()

In [2]:
np.random.rand()

0.46724496420989803

0 ile 1 arasında bir değer üretir.(1 dahil değildir)

In [4]:
np.random.rand(3,2)

array([[0.39101955, 0.37183463],
       [0.97489818, 0.45492026],
       [0.7660351 , 0.40048835]])

0 ile 1 arasındaki değerlerden (3,2) lik bir matris oluştuduk

### np.random.randint()

In [7]:
np.random.randint(2,size = 10)

array([0, 0, 0, 0, 1, 0, 0, 0, 1, 1])

0 ile 2 değerleri arasındaki int değerlerden oluşan 10 elemanlı bir array oluşturduk

In [8]:
np.random.randint(5,12,size = (4,2))

array([[ 7, 11],
       [ 5, 11],
       [ 6, 11],
       [ 9,  6]])

5 ile 12 değerleri arasında int değerlerden oluşan (4,2) lik bir matris oluşturduk

size parametresinin ilk değeri satır sayısını, ikinci değeri ise sütun sayısını belirtir

### np.random.choice()

In [9]:
names = ["veli","mehmet","ali","ahmet","hulya"]

In [10]:
np.random.choice(names,8)

array(['ali', 'hulya', 'hulya', 'ahmet', 'veli', 'veli', 'veli', 'ali'],
      dtype='<U6')

parametreye gönderilen listenin içinden rastgele 8 tane eleman seçerek bir array oluşturuldu (elemanlar tekrarlanabilir)

In [11]:
np.random.choice(names,(3,2))

array([['mehmet', 'ali'],
       ['mehmet', 'hulya'],
       ['hulya', 'ali']], dtype='<U6')

istenilen arrayi size olarak görülen parametreye boyut bilgisi gönderilerek matris oluşturulur