In [1]:
import numpy as np

## np.zeros

0 larla dolu bir array oluşturur

In [2]:
np.zeros(4)

array([0., 0., 0., 0.])

4 elemanlı 0'lardan oluşan bir array döndürür

In [3]:
# döndürülen array elemanları float değerlerden oluşur
# dtype parametresi ile veri tipi değiştirilebilir

In [4]:
np.zeros(4,dtype= int)

array([0, 0, 0, 0])

In [5]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

(3,2) lik 0'lardan oluşan bir matris döndürür(yine default floattır)

## np.ones

In [6]:
np.ones(5)

array([1., 1., 1., 1., 1.])

5 elemanlı 1'lerden oluşan bir array oluşturur

In [7]:
# döndürülen array elemanları float tipindedir
# dtype parametresi ile veri tipi değiştirilebilir

In [8]:
np.ones(5,dtype = int)

array([1, 1, 1, 1, 1])

In [9]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

(2,4) lük 1'lerden oluşan bir matris döndürür(yine default floattır)

## np.full

In [10]:
np.full((2,2),"Python")

array([['Python', 'Python'],
       ['Python', 'Python']], dtype='<U6')

(2,2) lik bir matris oluşturuldu ve içerisi "Python" ile dolduruldu

In [11]:
np.full((4,5),0) # =np.zeros((4,5))

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [12]:
np.full((3,1),1) # =np.zeros((3,1))

array([[1],
       [1],
       [1]])

## np.eye

parametredeki bilgiye göre bir kare matris oluşturarak köşegenleri 1 ile, geri kalanları ise 0 ile doldurur

In [13]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

(2,2) lik bir kare matris oluşturarak köşegenleri 1, geri kalanları ise 0 ile doldurduk

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
np.eye(4,k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

köşegeni 1 birim ileriye kaydırdık

In [16]:
np.eye(4,k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

köşegeni 1 birim geriye kaydırdık