## İki Numpy Dizisi ile İşlem Yapmak

In [1]:
import numpy as np

In [2]:
list1 = [2,4,6,8]

In [3]:
array1 = np.array(list1)
array1

array([2, 4, 6, 8])

In [4]:
list2 = [3,5,7,9]

In [5]:
array2 = np.array(list2)
array2

array([3, 5, 7, 9])

In [7]:
list3 = [1,2,3,4,5]

In [9]:
array3 = np.array(list3)
array3

array([1, 2, 3, 4, 5])

İki dizi ile işlem yapmak için boyutlar önemlidir

### Toplama

In [6]:
array1 + array2

array([ 5,  9, 13, 17])

Her iki dizinin aynı indeksteki elemanları birbirleri ile toplanır

In [10]:
array1 + array3

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

Eğer boyutlar eleman sayısı eşit olmazsa işlem hata döndürecektir

array1 arrayi 4 elemanlı bir vektörken array 3 vektörü ise 5 elemanlı bir vektördür bu yüzden toplama işlemi yapılamaz

##### Not: Boyut eşitliği kuralı her iki array arasındaki işlem için geçerlidir

In [12]:
array1 - array2

array([-1, -1, -1, -1])

array1 dizisinin elemanlarında array2 dizisinin elemanları çıkartıldı

### Çarpma

##### Not2: Numpy dizileriyle matris çarpımı ve numpy matris nesneleriyle matris çarpımı birbirinden farklıdır

In [26]:
array1

array([2, 4, 6, 8])

In [27]:
array2

array([3, 5, 7, 9])

In [13]:
array1 * array2

array([ 6, 20, 42, 72])

Çarpımda da yine bir iç işlem gerçekleşmiştir. Her bir eleman yine kendi indeksindeki elemanla çarpılmıştır

In [28]:
array3

array([1, 2, 3, 4, 5])

In [14]:
array1 * array3

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [15]:
# Boyut farkı yine hata döndürdü

In [16]:
# şimdi bir matris oluşturalım

In [23]:
m = np.matrix(([1,2],[5,7]))
m

matrix([[1, 2],
        [5, 7]])

In [24]:
m2 = np.matrix(([3,4],[1,2]))
m2

matrix([[3, 4],
        [1, 2]])

In [25]:
m * m2

matrix([[ 5,  8],
        [22, 34]])

* Matris çarpımında (0,0) indeksli elemanı bulmak için: m matrisindeki ilk satır ile m2 matrisindeki ilk sütun elemanları çarpılır ve çarpımlar toplanır ((1x3)+(2x1)). Bu işlem çarpım matrisinin (0,0) indeksli elemanını verir
* (0,1) indeksli elemanı bulmak için: m matrisindeki ilk satır ile m2 matrisindeki 1 indeksli sütun elemanları çarpılır ve çarpımlar toplanır ((1x4)+(1x2))
* (1,0) indeksli elemanı bulmak için: m matrisindeki 1 indeksli satır ile m2 matrisindeki ilk sütun çarpılır ve çarpımlar toplanır ((5x3)+(7x1))
* (1,1) indeksli elemanı bulmak için: m matrisindeki 1 indeksli satır ile m2 matrisindeki 1 indeksli sütun çarpılır ve çarpımlar toplanır ((5x4)+(7x2))

In [35]:
np.dot(m,m2)

matrix([[ 5,  8],
        [22, 34]])

çarpma işlemi için dot metodu da kullanılabilir

In [18]:
a = np.matrix([[1,2],[0,2],[3,1]])
a

matrix([[1, 2],
        [0, 2],
        [3, 1]])

In [19]:
# (3,2)lik bir matris oluşturduk

In [20]:
b = np.matrix([[4,3],[2,1]])
b

matrix([[4, 3],
        [2, 1]])

In [21]:
# (2,2)lik bir matris oluşturduk

In [31]:
b*a

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

iki matrisi çarptığımızda bir çarpım işlemi gerçekleşmez Çünkü boyutlar eşit değildir

In [32]:
a*b

matrix([[ 8,  5],
        [ 4,  2],
        [14, 10]])

a matrisi ile b matrisini çarptığımızda çarpım gerçekleşir çünkü a matrisi boyutu b matrisinden büyüktür

In [34]:
np.dot(a,b)

matrix([[ 8,  5],
        [ 4,  2],
        [14, 10]])

dot metodu ile de çarpım uygulanabilir

### Bölme

In [37]:
array1 / array2

array([0.66666667, 0.8       , 0.85714286, 0.88888889])

In [38]:
m / m2

matrix([[0.33333333, 0.5       ],
        [5.        , 3.5       ]])

In [39]:
a / b

ValueError: operands could not be broadcast together with shapes (3,2) (2,2) 

In [40]:
b / a 

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

* Normalde matrislerde bölme işlemi yapılmaz
* Eğer matrislerin boyu eşit ise iç içe bölme işlemi gerçekleştirilir. Bu bölme işlemi matris bölmesi değildir