In [1]:
import numpy as np

## Karşılaştırma Operatörleri

In [2]:
x = np.arange(1,6)
x

array([1, 2, 3, 4, 5])

karşılaştırma operatörleri array içindeki her bir eleman için değerlendirme yapar

In [3]:
x<2

array([ True, False, False, False, False])

In [4]:
x>2

array([False, False,  True,  True,  True])

In [7]:
x<=2

array([ True,  True, False, False, False])

In [8]:
x>=2

array([False,  True,  True,  True,  True])

In [9]:
x!=2

array([ True, False,  True,  True,  True])

In [10]:
x == 2

array([False,  True, False, False, False])

### İki dizi ile çalışmak

Söz konusu karşılaştırılan diziler aynı boyutta olmalıdır

In [12]:
y = np.arange(0,10,2)
y

array([0, 2, 4, 6, 8])

In [13]:
x

array([1, 2, 3, 4, 5])

In [14]:
y<x

array([ True, False, False, False, False])

In [15]:
y>x

array([False, False,  True,  True,  True])

In [16]:
y<=x

array([ True,  True, False, False, False])

In [17]:
y>=x

array([False,  True,  True,  True,  True])

In [18]:
y!=x

array([ True, False,  True,  True,  True])

In [19]:
y == x

array([False,  True, False, False, False])

## Mantıksal Operatörler

#### np.logical_and

In [20]:
dizi1 = np.arange(2,12,3)
dizi1

array([ 2,  5,  8, 11])

In [22]:
np.logical_and(dizi1>0,dizi1 == 5)

array([False,  True, False, False])

* mantıksal operatörler de array içindeki elemanlarla işlem yapar
* eğer logical_and şartlarından herhangi birini sağlamayan bir eleman varsa False değeri döndürür
* yani True almak için söz konusu elemanın her iki parametredeki şartı da sağlaması gereklidir

In [23]:
np.logical_and(dizi1>1,dizi1!= 4)

array([ True,  True,  True,  True])

elemanların hepsi her iki şartı da sağladığı için bütün elemanlar True değeri döndürür

#### np.logical_or

In [25]:
np.logical_or(dizi1 == 12,dizi1>1)

array([ True,  True,  True,  True])

or operatöründeki şartlardan herhangi birini sağlayan eleman True değerini döndürür

#### np.logical_not

In [27]:
dizi1

array([ 2,  5,  8, 11])

In [29]:
np.logical_not(dizi1>0)

array([False, False, False, False])

True döndürülecek elemanlardan False,False döndürecek elemanlardan ise True değerini döndürür

In [30]:
np.logical_not(dizi1>=15)

array([ True,  True,  True,  True])

elemanların hiçbiri şartı sağlamıyor yani False değeri döndürüyor fakat not ile bu değerleri tekrar tersine çevirdik